Replace native Alerts with a Toast
filiptronicek/iclip-mobile pull request #172
Opened 2021-06-26 19:55 UTC by filiptronicek

Awesone toasts. Let's toast to the toasts!

- [ ] Dark mode would be cool

2021-06-27 06:50 UTC, bigint commented
Love to see screenshots 🤗

2021-06-27 08:56 UTC, filiptronicek commented
Sure thing, @bigint!
![image](https://user-images.githubusercontent.com/29888641/123538655-49b90480-d736-11eb-826c-0d6415b13497.jpeg)
![image](https://user-images.githubusercontent.com/29888641/123538662-50477c00-d736-11eb-9ac1-b6fd50c00cca.jpeg)

2021-07-11 14:13 UTC, bigint requested changes

2021-07-11 14:13 UTC, bigint commented on pages/FilePage.js
> +          text2: `Permission to access the camera roll is required!`,
@filiptronicek Do you think backtick is needed here? If you see `text1` its in dquote 🤔

2021-07-11 14:13 UTC, bigint commented on pages/FilePage.js
> +          text2: `Permission to access the camera is required!`,
Here too!

2021-07-11 14:13 UTC, bigint commented on pages/FilePage.js
> +                text2: `Got the error ${res.status}.`,
Suitable for this scenario :D

2021-07-11 14:13 UTC, bigint commented on pages/HomeScreen.js
> +                text2: "We are getting too many requests from you.",
Purrrfect!

2021-07-11 14:13 UTC, bigint commented
Others LGTM 🚀

2021-07-11 15:10 UTC, filiptronicek commented
Dark mode maybe later, aligator

2021-07-11 15:11 UTC, merged